---
title: Europawahl 2024
author: SPD Zürich
email: kontat@spd-zuerich.ch
description: "Eure Stimme bei der Europawahl 2024: Informationen für Deutsche Staatsangehörige in der Schweiz"
baseurl: "/"
url: europawahl.ch
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
